// One-off vendoring of the UI fonts (scenes UI spec §2.7): Cinzel, Alegreya and Literata as
// woff2, latin + latin-ext subsets, copied from the @fontsource 5.3.0 packages on jsDelivr (the
// same files npm would install: unmodified Google Fonts builds). Writes public/fonts/<pkg>/
// (+ the family's OFL licence as OFL.txt) and generates src/styles/fonts.css.
// Run from web/ with `scripts/npm.sh run fonts`. The output is committed, so neither the Docker
// build nor the running app ever downloads a font.
import { mkdir, writeFile } from 'node:fs/promises';

const VERSION = '5.3.0';
const RANGES = {
  latin:
    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  'latin-ext':
    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
};
const FACES = [
  { family: 'Cinzel', pkg: 'cinzel', weight: 600, style: 'normal' },
  { family: 'Cinzel', pkg: 'cinzel', weight: 700, style: 'normal' },
  { family: 'Alegreya', pkg: 'alegreya', weight: 400, style: 'normal' },
  { family: 'Alegreya', pkg: 'alegreya', weight: 400, style: 'italic' },
  { family: 'Alegreya', pkg: 'alegreya', weight: 700, style: 'normal' },
  { family: 'Literata', pkg: 'literata', weight: 400, style: 'normal' },
  { family: 'Literata', pkg: 'literata', weight: 600, style: 'normal' },
];

const cdn = (pkg, path) => `https://cdn.jsdelivr.net/npm/@fontsource/${pkg}@${VERSION}/${path}`;

async function download(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

for (const pkg of [...new Set(FACES.map((f) => f.pkg))]) {
  await mkdir(`public/fonts/${pkg}`, { recursive: true });
  await writeFile(`public/fonts/${pkg}/OFL.txt`, await download(cdn(pkg, 'LICENSE')));
}

const blocks = [];
for (const f of FACES) {
  for (const subset of ['latin-ext', 'latin']) {
    const file = `${f.pkg}-${subset}-${f.weight}-${f.style}.woff2`;
    await writeFile(`public/fonts/${f.pkg}/${file}`, await download(cdn(f.pkg, `files/${file}`)));
    blocks.push(
      [
        '@font-face {',
        `  font-family: '${f.family}';`,
        `  font-style: ${f.style};`,
        `  font-weight: ${f.weight};`,
        '  font-display: swap;',
        `  src: url('/fonts/${f.pkg}/${file}') format('woff2');`,
        `  unicode-range: ${RANGES[subset]};`,
        '}',
      ].join('\n'),
    );
    console.log(`fonts: ${file}`);
  }
}

await mkdir('src/styles', { recursive: true });
await writeFile(
  'src/styles/fonts.css',
  `/* Generated by web/scripts/vendor-fonts.mjs (@fontsource ${VERSION}) - do not edit by hand. */\n\n${blocks.join('\n\n')}\n`,
);
