// One-off vendoring of the UI fonts (scenes UI spec §2.7): Cinzel, Alegreya and Literata as
// woff2, latin + latin-ext subsets, copied from the @fontsource 5.3.0 packages on jsDelivr (the
// same files npm would install: unmodified Google Fonts builds). Writes public/fonts/<pkg>/
// (+ the family's OFL licence as OFL.txt) and generates src/styles/fonts.css.
// Run from web/ with `scripts/npm.sh run fonts`. The output is committed, so neither the Docker
// build nor the running app ever downloads a font.
//
// Downloads land in a scratch dir under .cache/ (git-ignored, outside public/ so the Docker build
// - which only ever copies public/ - can never ship a partial download if this script is
// interrupted before it cleans up) and are only swapped into public/fonts once every file has
// downloaded successfully. The swap itself never leaves public/fonts missing even if it fails
// partway: the old tree is moved aside to a backup (under .cache/, next to the scratch dir, so
// both moves below are plain renames and nothing stray is ever left in public/) before the new
// one is moved in, and is only discarded once the new tree is safely in place; a failed move-in
// restores it.
import { mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';

const VERSION = '5.3.0';
const RANGES = {
  latin:
    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  'latin-ext':
    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
};
const FACES = [
  { family: 'Cinzel', pkg: 'cinzel', weight: 600, style: 'normal' },
  { family: 'Cinzel', pkg: 'cinzel', weight: 700, style: 'normal' },
  { family: 'Alegreya', pkg: 'alegreya', weight: 400, style: 'normal' },
  { family: 'Alegreya', pkg: 'alegreya', weight: 400, style: 'italic' },
  { family: 'Alegreya', pkg: 'alegreya', weight: 700, style: 'normal' },
  { family: 'Literata', pkg: 'literata', weight: 400, style: 'normal' },
  { family: 'Literata', pkg: 'literata', weight: 600, style: 'normal' },
];

const cdn = (pkg, path) => `https://cdn.jsdelivr.net/npm/@fontsource/${pkg}@${VERSION}/${path}`;

async function download(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

const rand = randomBytes(4).toString('hex');
const scratch = `.cache/vendor-fonts-download-${rand}`;
// Final review M14: the backup of the old tree lives under .cache/ too (same filesystem as the
// scratch dir, which is already renamed into public/ below), so a crash between the two renames
// can never leave a stray backup inside public/ for the Docker build to ship.
const backup = `.cache/fonts-backup-${rand}`;

try {
  for (const pkg of [...new Set(FACES.map((f) => f.pkg))]) {
    await mkdir(`${scratch}/${pkg}`, { recursive: true });
    await writeFile(`${scratch}/${pkg}/OFL.txt`, await download(cdn(pkg, 'LICENSE')));
  }

  const blocks = [];
  for (const f of FACES) {
    for (const subset of ['latin-ext', 'latin']) {
      const file = `${f.pkg}-${subset}-${f.weight}-${f.style}.woff2`;
      await writeFile(`${scratch}/${f.pkg}/${file}`, await download(cdn(f.pkg, `files/${file}`)));
      blocks.push(
        [
          '@font-face {',
          `  font-family: '${f.family}';`,
          `  font-style: ${f.style};`,
          `  font-weight: ${f.weight};`,
          '  font-display: swap;',
          `  src: url('/fonts/${f.pkg}/${file}') format('woff2');`,
          `  unicode-range: ${RANGES[subset]};`,
          '}',
        ].join('\n'),
      );
      console.log(`fonts: ${file}`);
    }
  }

  // Everything downloaded: swap the scratch dir in for public/fonts and write fonts.css. Only
  // this last stretch touches the committed tree.
  let hadOldTree = true;
  try {
    await rename('public/fonts', backup);
  } catch (err) {
    if (err.code === 'ENOENT') hadOldTree = false; // nothing committed yet - nothing to back up
    else throw err;
  }
  try {
    await rename(scratch, 'public/fonts');
  } catch (err) {
    if (hadOldTree) await rename(backup, 'public/fonts'); // restore: never leave public/fonts missing
    throw err;
  }
  if (hadOldTree) await rm(backup, { recursive: true, force: true });

  await mkdir('src/styles', { recursive: true });
  await writeFile(
    'src/styles/fonts.css',
    `/* Generated by web/scripts/vendor-fonts.mjs (@fontsource ${VERSION}) - do not edit by hand. */\n\n${blocks.join('\n\n')}\n`,
  );
} catch (err) {
  await rm(scratch, { recursive: true, force: true }).catch(() => {});
  throw err;
}
