// Scene data types (scenes UI spec §4). Coordinates are "art %": 0-100 of the 16:9 art frame,
// x left to right, y top to bottom, so scene data survives any art swap of the same framing.
import type { RouteName } from '../routes';
import type { CampResponse, WorldCatalog } from '../world/types';

export type Pt = [number, number];

export interface EllipseShape {
  kind: 'ellipse';
  cx: number;
  cy: number;
  rx: number;
  ry: number;
}

export interface PolygonShape {
  kind: 'polygon';
  points: Pt[];
}

export type HotspotShape = EllipseShape | PolygonShape;

/** Hotspot id -> shape. The `<scene>.shapes.ts` files are exactly this, generated by `?edit`. */
export type ShapeMap = Record<string, HotspotShape>;

/** Axis-aligned box in art %. */
export interface Box {
  x: number;
  y: number;
  w: number;
  h: number;
}

/** Parallax plane: 0 = the background plane (never moves), 1-3 = cut-out layers (spec: ≤ 3). */
export type Depth = 0 | 1 | 2 | 3;
export type IdlePreset = 'none' | 'bob' | 'sway' | 'breathe';
export type FxPreset = 'none' | 'embers' | 'dust';
export type SceneId = 'camp';

/** A positioned cut-out image. `x` = horizontal centre, `y` = bottom edge (feet on the ground),
 *  `scale` = width, all in art %. */
export interface SceneLayerDef {
  id: string;
  src: string;
  /** '' for pure decoration. */
  alt: string;
  x: number;
  y: number;
  scale: number;
  depth: Depth;
  idle: IdlePreset;
}

/** What hotspot state functions may read. `camp` is null until /camp has loaded. */
export interface SceneContext {
  camp: CampResponse | null;
  catalog: WorldCatalog | null;
}

export interface HotspotState {
  visible: boolean;
  locked: boolean;
  /** Draws the stronger "something new here" glow. */
  isNew: boolean;
  badge: number | null;
  /** Short second line under the place name (dragon name, reward, counts). */
  caption: string | null;
}

export const IDLE_HOTSPOT: HotspotState = { visible: true, locked: false, isNew: false, badge: null, caption: null };

export interface HotspotDef {
  id: string;
  /** Place name shown on the label (Cinzel caps). */
  label: string;
  target: RouteName;
  shape: HotspotShape;
  labelPos: 'above' | 'below';
  state: (ctx: SceneContext) => HotspotState;
}

export interface SceneDef {
  id: SceneId;
  /** Marble plaque text. */
  title: string;
  background: string;
  layers: SceneLayerDef[];
  hotspots: HotspotDef[];
  ambience: { particles: FxPreset; music: string | null };
  /** Dialogue event keys for UI5 (content/dialogue/*.json); unused in UI1. */
  narrator: { enter: string | null; firstVisit: string | null };
  /** Backgrounds the player is likely to open next (spec §4 performance). */
  preload: string[];
}

export type SpeakerId = 'dragon' | 'pythia' | 'owl' | 'eris';

export interface DialogueLine {
  speaker: SpeakerId;
  name: string;
  portrait: string;
  portraitFilter?: string;
  text: string;
}
